---
title: 'The CARE principles and open data'
teaching: 10
exercises: 2
---

::: questions
-   What is Indigenous data sovereignty?
-   What are the CARE principles?
-   What is Local Contexts Hub, and how can we use it to implement the CARE principles in our work? 
:::

::: objectives
After following this episode, we intend that participants will be able to:

1.  Articulate the mission of Local Contexts Hub in the context of the CARE and FAIR principles
2.  Apply Bio-Cultural and Traditional Knowledge Notices appropriately to datasets
3.  Create an account on Local Contexts Hub
4.  Create a project on Local Contexts Hub
5.  Query the Local Contexts Hub API to link a dataset with project IDs on Local Contexts Hub
:::

## Indigenous data soverginty

## The CARE Principles

### Collective benefit

### Authority to control

### Responsibility

### Ethics

## Local Contexts Hub

### Labels

https://localcontexts.org/labels/traditional-knowledge-labels/

### Notices

https://localcontexts.org/notices/aboutnotices/

https://localcontexts.org/notice-in-use-maine-edna/


## The Local Contexts Hub API


::: keypoints
-   "Be FAIR and CARE": The CARE principles (**C**ollective benefit, **A**uthority to control, **R**esponsibility, and **E**thics) are part of a framework emphasizing Indigenous rights and interests in the context of data sharing ecosystems.
-   Local Contexts Hub provides Labels and Notices for learning more about and engaging with Indigenous data in accordance with the CARE principles. 

:::
