---
title: "Connecting different data types"
teaching: 10
exercises: 2
editor_options: 
  markdown: 
    wrap: 50
---



::: questions

- What questions and analyses can we explore by linking multiple data types together?
- How do we determine if our data can be linked?
- How do we actually link different data types together?
- How do we analyze, visualize, and interpret multiple data types concurrently? 

:::::::::::::


::: objectives

After following this episode, we intend that participants will be able to:

1. Generate ideas for scientific questions that can be answered using 2 or more of the data types we have covered in previous episodes
2. Identify considerations regarding the cross-compatibility of data from different sources
3. Use spatial and taxonomic tools to link data of different types
4. Calculate and visualize joint diversity indices for multiple data types simultaneously
5. Interpret these results in scientific context

::::::::::::::



# Motivation: Why combine data types?

::: instructor

Think-pair-share

Segueing into the simulated Hawaii data

:::

::: discussion

What kinds of questions can we imagine answering using multipe data types at once?

:::


## Show demo visualization of Hawaii sim data

# Linking different data types

## Checking the compatibility of data types

### Taxonomic overlap

### Taxonomic consistency

### Spatial extent

### Others??

## Linking data types

### Resources for resolving inconsistencies

### left_join

(being slightly flip here, but this is the heart of it, right?)

# Analyzing and visualizing joint data types

## Hill numbers for multidim data

### Discussion/lecture

### Calculating Hills

## Visualizing multiple data types

### Joing vis plots

## Interpretation

::: discussion

Discuss Hawaii interp

:::

# Challenge: using other data sets

::: instructor

Here I was thinking to generate a few more toy data sets using RoLE as foreshadowing of days 3-4.

:::



# Recap

::: keypoints

- Considering multiple data types at once can answer a unique and rapidly evolving set of questions
- Data types do need to be (minimally) compatible; there are resources/approaches for reconciling not-fully-compatible data
- Hill numbers provide a unified framework for the analysis and visualization of different data types as part of one question


:::
    
